Repository mayankwalia/HacktoberFest-22, pull requests merged in 2022-10, with the labels that each got.

#3 added snake game in python and javascript
  Projects/JavaScript/index.html
  Projects/JavaScript/snake.js
  Projects/Python/Snakegame.py
Labels: Hacktoberfest, hacktoberfest-accepted, lang-py

#5 Added snakegame in c
  Projects/Snakegame.c
Labels: Hacktoberfest, hacktoberfest-accepted, lang-c

#4 Tic Tac Toe using .NET
  .vs/HacktoberFest-22/FileContentIndex/0f9d1493-5dc1-44d2-8f49-27d4f5b809de.vsidx
  .vs/HacktoberFest-22/FileContentIndex/read.lock
  .vs/slnx.sqlite
  Projects/C#/TIC-TAC-TOE/obj/Debug/.NETFramework,Version=v4.8.AssemblyAttributes.cs
  Projects/C#/TIC-TAC-TOE/obj/Debug/TIC-TAC-TOE.csproj.AssemblyReference.cache
  Projects/C#/TIC-TAC-TOE/obj/Release/.NETFramework,Version=v4.8.AssemblyAttributes.cs
  Projects/C#/TIC-TAC-TOE/obj/Release/TIC-TAC-TOE.csproj.AssemblyReference.cache
Labels: Hacktoberfest, hacktoberfest-accepted, lang-.net

#8 added hangman game in python
  Projects/Python/HangMan/hangman.py
  Projects/Python/HangMan/words.txt
Labels: Hacktoberfest, hacktoberfest-accepted, lang-py

#10 Added web devlopment project
  Projects/movie seat booking/index.html
  Projects/movie seat booking/script.js
  Projects/movie seat booking/style.css
Labels: Hacktoberfest, hacktoberfest-accepted, lang-js

#9 Create word_char_counter.java
  Projects/word_char_counter.java
Labels: Hacktoberfest, hacktoberfest-accepted, lang-java

#13 Added space quiz app
  Projects/JavaScript/QuizGame-main/README.md
  Projects/JavaScript/QuizGame-main/index.html
  Projects/JavaScript/QuizGame-main/landingpageStyles.css
  Projects/JavaScript/QuizGame-main/mainquiz.html
  Projects/JavaScript/QuizGame-main/mainquizScript.js
  Projects/JavaScript/QuizGame-main/mainquizStyles.css
  Projects/JavaScript/QuizGame-main/space.jpeg
  Projects/JavaScript/QuizGame-main/updated_Astronaut.png
Labels: Hacktoberfest, hacktoberfest-accepted, lang-js, lang-html

#12 Added web development project
  .vscode/settings.json
  Projects/movie seat booking/index.html
  Projects/movie seat booking/script.js
  Projects/movie seat booking/style.css
Labels: lang-js

#14 Added: Expense Tracker app
  Projects/JavaScript/Expense-Calculator-main/README.md
  Projects/JavaScript/Expense-Calculator-main/index.html
  Projects/JavaScript/Expense-Calculator-main/script.js
  Projects/JavaScript/Expense-Calculator-main/style.css
Labels: Hacktoberfest, Hacktoberfest2022, hacktoberfest-accepted, lang-js
